### ISSUE TITLE
Adding a 20 minute suspend duration

### ISSUE THREAD

**Issue by jimc404** [pradeep-mishra/tab_suspender_firefox#1]
First of all, Thanks for making this extension! Right after installing this, I realised that I should have done that much sooner.

The extension does exactly what it says, my one very minor gripe has been the fact that the last two delays are a bit too spaced apart. If I end up reading a long article the 10 minute delay makes me reload everything else, whereas the 30 minute delay leaves many tabs active eating up significant amount of RAM. 

So, would it be possible to add a 20 minute delay (there are more customizable fixes, while they'll be great to have, I'll be pretty content with just this one addition)

**Comment by pradeep-mishra** [comment]
sure will do that, thanks for your feedback.

**Comment by pradeep-mishra** [comment]
Done.
please install v1.6

**Comment by jimc404** [comment]
Works like a charm, thanks!
