### ISSUE TITLE
Why does this extension now need data for all sites permission?

### ISSUE THREAD

**Issue by Bandit** [pradeep-mishra/tab_suspender_firefox#2]
As of the 1.6 update

**Comment by jnm** [comment]
I'm wondering if it was added for debugging and accidentally left in for the release? The actual changes for the 1.6 update are small and innocuous:
https://github.com/pradeep-mishra/tab_suspender_firefox/commit/7808339d0f05e032207ce3182fb38518b9570836?w=1

I don't use the URL whitelisting feature, so I've declined the update for now.

**Comment by Bandit** [comment]
Yeah I saw that. I also noticed version 1.5 (the version I'm now using) was never added to the repo?

**Comment by pradeep-mishra** [comment]
1.5 was also published in github but i did not put that in comment.
in version 1.6 i have added 15,20 minutes and 1 hour options in suspend
after dropdown.

**Comment by Bandit** [comment]
Ok but why did you add the "all data for all sites" permission?

https://github.com/pradeep-mishra/tab_suspender_firefox/commit/7808339d0f05e032207ce3182fb38518b9570836#diff-4b1eb3dc48c4e16d49db5b42298fe654R20

**Comment by pradeep-mishra** [comment]
I dont remember I’ll check, it might be there for URL whitelisting or any
unfinished feature.
if its not required for now then will remove in 1.7

**Comment by LtqxWYEG** [comment]
Yeah. I hope you remove it again. Until then I'm not updating. I already chose your addon over others because they needed this permission for no reason. There really is no reason for it.

**Comment by LtqxWYEG** [comment]
Yeah. I hope you remove it again. Until then I'm not updating. I already chose your addon over others because they needed this permission for no reason. There really is no reason for it.

**Comment by LtqxWYEG** [comment]
Yeah. I hope you remove it again. Until then I'm not updating. I already chose your addon over others because they needed this permission for no reason. There really is no reason for it.

**Comment by LtqxWYEG** [comment]
Yeah. I hope you remove it again. Until then I'm not updating. I already chose your addon over others because they needed this permission for no reason. There really is no reason for it.

**Comment by pradeep-mishra** [comment]
removed all site permission
please update to v 1.7

**Comment by jnm** [comment]
thank you!

**Comment by LtqxWYEG** [comment]
Thank you :)
