### ISSUE TITLE
Option for choosing if tab should be unsuspended automatically when it is visited

### ISSUE THREAD

**Issue by IlyaOrson** [pradeep-mishra/tab_suspender_firefox#5]
First of all, thank you for this extension. It is incredibly useful!

I find fairly common to have many tabs open and switch between neighbouring tabs quickly with `Ctrl + Tab`, `Ctrl + Shift + Tab` or shortcuts like that. Reloading intermediate suspended tabs while moving like this makes this workflow cumbersome. It becomes necessary to use a tab manager but it is also not as snappy. It would be nice to be able to visit suspended tabs without necessarily reloading them for this purpose.

The chrome extension called The Great Sustender allows this as an option where the user reloads explicitly the tab with a click or a refresh. Maybe something like this would be a worthwhile addition?

**Comment by pradeep-mishra** [comment]
I have used Firefox extension's native discard API, where we do not have control to over un-suspend the tab, it automatically does it whenever we visits the tab.
The Great Suspender do not rely on that API, it just take a snapshot and load that image in that tab and onclick again reload the URL which was there on that tab.
